service: serverless-api-lambda-dynamodb-example

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: us-west-2

functions:
  hello:
    handler: handler.getAccount
    events:
      - http:
          path: accounts/{proxy+}
          method: get

